### PR TITLE
Fix bit/byte mixup for SpirvDebugTypeMember.offset

### PR DESCRIPTION
**Pull request by ben-clayton**
Rename `offset` variables to `offsetInBits` to try avoiding this sort of mistake in the future.

### CODE REVIEW

**Review by jaebaek — APPROVED** [review]
Ah .. I might forget to multiply by `8`. Nice catch!

I will consider adding unit tests to check this type of mistakes.

**Comment by ben-clayton** [comment]
Thanks for the review. FYI: I don't have permissions to land.

**Comment by jaebaek** [comment]
Sure. I think we have to submit #310 first. After that, we can rebase this PR and I can submit it. I will ping you when it is ready to rebase.

**Comment by ehsannas** [comment]
Looks like this test should also be updated FileTest.RichDebugInfoCbuffer

**Comment by ben-clayton** [comment]
Fixed the `FileTest.RichDebugInfoCbuffer` test.
Rebased onto Jaebaek's PR to check the presubmits pass. Will rebase again once #310 lands.

**Comment by ben-clayton** [comment]
Rebased.

**Pull request merged**
