### PR TITLE
[spirv] Translate bitwise operators

### PR DESCRIPTION
**Pull request by antiagainst**
* Covers ~, &, |, ^, <<, >>, &=, |=, ^=, <<=, >>=
* For int/uint and vector of int/uint

### CODE REVIEW

**Comment by antiagainst** [comment]
Actually the frontend will make sure both operands are integer (vector) values, by either implicit casting or error out.

For the following code
```hlsl
void main() {
  bool2 a, b;
  b &= a;

  //float3 c, d;
  //d |= c;
}
```

The generated AST is

```rust
TranslationUnitDecl 0x194796ebb10 <<invalid sloc>> <invalid sloc>
`-FunctionDecl 0x1947b9fcbd0 <hlsl.hlsl:4:1, line:8:1> line:4:6 main 'void ()'
  `-CompoundStmt 0x1947ba00338 <col:13, line:8:1>
    |-DeclStmt 0x1947b9ffa38 <line:5:3, col:13>
    | |-VarDecl 0x1947b9ff930 <col:3, col:9> col:9 used a 'bool2':'vector<bool, 2>'
    | `-VarDecl 0x1947b9ff9b0 <col:3, col:12> col:12 used b 'bool2':'vector<bool, 2>'
    `-CompoundAssignOperator 0x1947ba00300 <line:6:3, col:8> 'bool2':'vector<bool, 2>' lvalue '&=' ComputeLHSTy='vector<bool, 2>' ComputeResultTy='vector<bool, 2>'
      |-DeclRefExpr 0x1947b9ffa50 <col:3> 'bool2':'vector<bool, 2>' lvalue Var 0x1947b9ff9b0 'b' 'bool2':'vector<bool, 2>'
      `-ImplicitCastExpr 0x1947ba002e8 <col:8> 'vector<bool, 2>' <HLSLCC_IntegralToBoolean>
        `-ImplicitCastExpr 0x1947ba002d0 <col:8> 'vector<int, 2>' <HLSLCC_IntegralCast>
          `-ImplicitCastExpr 0x1947b9ffaa0 <col:8> 'bool2':'vector<bool, 2>' <LValueToRValue>
            `-DeclRefExpr 0x1947b9ffa78 <col:8> 'bool2':'vector<bool, 2>' lvalue Var 0x1947b9ff930 'a' 'bool2':'vector<bool, 2>
```

If we uncomment the `float3` code, it will error out with:
```
hlsl.hlsl:9:5: error: int or unsigned int type required
  d |= c;
    ^
```

So we should be safe for the HLSL semantic check side with the help of the front end.

**Comment by ehsannas** [comment]
Cool!

**Comment by antiagainst** [comment]
Oh, wait. For the above case, `b &= a` does need special handling b/c the rhs is casted three times (`LValueToRValue`, bool2 -> int2, and then int2 -> bool2). So that's actually an interesting case that will make the current codegen go wrong I believe. Thanks for spotting this! :)

But for the normal assignment `b = a & b`, the AST is like

```rust
    `-BinaryOperator 0x1947b9fd050 <line:6:3, col:11> 'bool2':'vector<bool, 2>' '='
      |-DeclRefExpr 0x1947b9fc720 <col:3> 'bool2':'vector<bool, 2>' lvalue Var 0x1947b9fc680 'b' 'bool2':'vector<bool, 2>'
      `-ImplicitCastExpr 0x1947b9fd038 <col:7, col:11> 'vector<bool, 2>' <HLSLCC_IntegralToBoolean>
        `-BinaryOperator 0x1947b9fd010 <col:7, col:11> 'vector<int, 2>' '&'
          |-ImplicitCastExpr 0x1947b9fcfe0 <col:7> 'vector<int, 2>' <HLSLCC_IntegralCast>
          | `-ImplicitCastExpr 0x1947b9fc798 <col:7> 'bool2':'vector<bool, 2>' <LValueToRValue>
          |   `-DeclRefExpr 0x1947b9fc748 <col:7> 'bool2':'vector<bool, 2>' lvalue Var 0x1947b9fc600 'a' 'bool2':'vector<bool, 2>'
          `-ImplicitCastExpr 0x1947b9fcff8 <col:11> 'vector<int, 2>' <HLSLCC_IntegralCast>
            `-ImplicitCastExpr 0x1947b9fc7b0 <col:11> 'bool2':'vector<bool, 2>' <LValueToRValue>
              `-DeclRefExpr 0x1947b9fc770 <col:11> 'bool2':'vector<bool, 2>' lvalue Var 0x1947b9fc680 
```
It's clear both operands are casted to int2 for `BinaryOperator`. So it should be fine.

**Comment by antiagainst** [comment]
#thejoyofcompoundassignment

**Comment by antiagainst** [comment]
Created #89 to handle the compound bitwise assignment for boolean values. I'll merge this and address #89 in another PR.

**Pull request merged**
