### PR TITLE
[linux-port] Roll back PR #171.

### PR DESCRIPTION
**Pull request by ehsannas**
It seems that there is an issue with command line processing, causing
the following failure:

LLVM ERROR: IO failure on output stream.

I'll file a case to address this hack.

### CODE REVIEW

**Comment by pow2clk** [comment]
oh that's a relief. I was running into this too. :+1:

**Comment by ehsannas** [comment]
@pow2clk , sorry about that. The ride can be a bit bumpy until we can get all the bots to pass.

The bots are currently not running tests because our unit tests cause some sort of segfault. In this CL I am adding a simple smoke-test to the bots until we can get the unit tests up and running.

**Comment by ehsannas** [comment]
hmm.. that's odd, why isn't appveyor showing up for this PR... maybe it doesn't like the change i made to its config file..

**Comment by ehsannas** [comment]
All right, i see the pretty output i expect at the end of the log:
https://api.travis-ci.org/v3/job/379884593/log.txt

**Comment by ehsannas** [comment]
I am also disabling the linux/gcc builds on Travis until the gcc build can actually pass. I'd like to start seeing the real Linux/clang build status (and the real Windows build status) here.

**Pull request merged**
